Shop_Stationery/Models/Classes/ClassesUser/ConfirmCode/ConfirmCode.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop_Stationery.Models.Classes.ClassesUser.ConfirmCode
{
    public class ConfirmCode
    {
        public string Code { get; set; }
        public bool Confirm  { set; get; }
        public string PhoneNumber { get; set; }
        public DateTime TimeExpiration { get; set; }
    }
}

Shop_Stationery/Controllers/User/Signup/SignupController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Shop_Stationery.Models.ViewModelUser.ViewModelSignup;
using bll.User.bl_Signup;
using Entity;
using Entity.UserApp;
using static Entity.UserApp.userapp;
using Shop_Stationery.Models.ViewModelUser.ViewModelSubmitPassword;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Shop_Stationery.Models.Classes.ClassesUser.ConfirmCode;
using Microsoft.AspNetCore.Authorization;
using Shop_Stationery.Models.Classes.ClassesUser.SMS;
using System.Security.Claims;

namespace Shop_Stationery.Controllers.User.Signup
{
    public class SignupController : Controller
    {
        private readonly UserManager<UserApp> _userManager;
        private readonly SignInManager<UserApp> _SignInManager;

        public SignupController(UserManager<UserApp> userManager , SignInManager<UserApp> SignInManager)
        {
            _userManager = userManager;
            _SignInManager = SignInManager;
        }

        /////////////////////////
        #region ConfirmCodeAction

        [Route("/Signup/ConfirmCode")]
        public IActionResult ConfirmCode()
        {
            TempData["ConfirmCode"] = TempData["ConfirmCode"];
            TempData.Keep();
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("DashBoard", "Acccount");
            }
            //var ConfirmCode = JsonConvert.DeserializeObject<ConfirmCode>(HttpContext.Session.GetString("ConfirmCode"));
            var ConfirmCode = JsonConvert.DeserializeObject<ConfirmCode>((string)TempData["ConfirmCode"]);
            ViewBag.ConfirmCode = JsonConvert.SerializeObject(ConfirmCode);
            if (ConfirmCode.PhoneNumber == null)
            {
                return Redirect("/PhoneNumber");
            }
            if (ConfirmCode.TimeExpiration <= DateTime.Now)
            {
                Random random = new Random();
                int rnd = random.Next(10000, 99999);
                ConfirmCode.Code = rnd.ToString();
                ConfirmCode.TimeExpiration = DateTime.Now.AddMinutes(3);
                SMS s = new SMS();
                ViewBag.Code = rnd.ToString();
                bool ResultSendCode = s.SendConfirmCode(rnd.ToString(), ConfirmCode.PhoneNumber);
                ViewBag.ConfirmCode = JsonConvert.SerializeObject(ConfirmCode);
                TempData["ConfirmCode"] = JsonConvert.SerializeObject(ConfirmCode);
                TempData.Keep();

            }
            return View();
        }

        [Route("/Signup/ConfirmCode")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmCode(ViewModelExistPhoneNumber PhoneNumber)
        {
            TempData["ConfirmCode"] = TempData["ConfirmCode"];
            TempData.Keep();
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("DashBoard", "Acccount");
            }
            //var ConfirmCode = JsonConvert.DeserializeObject<ConfirmCode>(HttpContext.Session.GetString("ConfirmCode"));
            var ConfirmCode = JsonConvert.DeserializeObject<ConfirmCode>((string)TempData["ConfirmCode"]);
            ViewBag.ConfirmCode = JsonConvert.SerializeObject(ConfirmCode);
            if (PhoneNumber.ConfirmCode == null)
            {
                ModelState.AddModelError(string.Empty, "لطفا اطلاعات را تکمیل کنید");
                return View(PhoneNumber);
            }
            if (ConfirmCode.TimeExpiration <= DateTime.Now)
            {
                ModelState.AddModelError(string.Empty, "کد نامعتبر است");
                return View(PhoneNumber);
            }
            if (PhoneNumber.ConfirmCode != ConfirmCode.Code )
            {
                ModelState.AddModelError(string.Empty, "کد نامعتبر است");
                return View(PhoneNumber);
            }
            else
            {
                ConfirmCode confirm = new ConfirmCode();
                confirm = ConfirmCode;
                confirm.Confirm = true;
                TempData["ConfirmCode"] = JsonConvert.SerializeObject(ConfirmCode);
                //HttpContext.Session.SetString("ConfirmCode", JsonConvert.SerializeObject(confirm));
                return RedirectToAction(nameof(SubmitPassword));
            }
        }
        #endregion
        /////////////////////////
        

        /////////////////////
        #region SubmitPasswordAction
        [Route("/Signup/SubmitPassword")]
        [HttpGet]
        public IActionResult SubmitPassword()
        {
            TempData["ConfirmCode"] = TempData["ConfirmCode"];
            TempData.Keep();
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("DashBoard", "Acccount");
            }
            //var ConfirmCode = JsonConvert.DeserializeObject<ConfirmCode>(HttpContext.Session.GetString("ConfirmCode"));
            var ConfirmCode = JsonConvert.DeserializeObject<ConfirmCode>((string)TempData["ConfirmCode"]);
            if (!ConfirmCode.Confirm)
            {
                return NotFound();
            }

            if (ConfirmCode.PhoneNumber == null)
            {
                return NotFound();
            }
            return View();
        }
        [Route("/Signup/SubmitPassword")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitPassword(ViewModelSubmitPassword Passwords)
        {
            TempData["ConfirmCode"] = TempData["ConfirmCode"];
            TempData.Keep();
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("DashBoard", "Acccount");
            }
            //var ConfirmCode = JsonConvert.DeserializeObject<ConfirmCode>(HttpContext.Session.GetString("ConfirmCode"));
            var ConfirmCode = JsonConvert.DeserializeObject<ConfirmCode>((string)TempData["ConfirmCode"]);
            if (!ConfirmCode.Confirm)
            {
                return NotFound();
            }
            if (Passwords.Password == null || Passwords.PasswordAgain == null)
            {
                ModelState.AddModelError(string.Empty, "لطفا اطلاعات را تکمیل کنید");
                return View();
            }
            else if (Passwords.Password.Trim() != Passwords.PasswordAgain.Trim() )
            {
                ModelState.AddModelError(string.Empty, "رمز ها باید یکی باشند");
                return View();
            }
            else if (ConfirmCode.TimeExpiration <= DateTime.Now)
            {
                ModelState.AddModelError(string.Empty, "کد نامعتبر است");
                return View();
            }
            else
            {
                bl_Signup bl_Signup = new bl_Signup(_userManager);
                UserApp user = new UserApp()
                {
                    UserName = ConfirmCode.PhoneNumber.Trim(),
                    PasswordHash = Passwords.Password.Trim()
                };
                var result = await bl_Signup.SignUp(user);
                if (result == "کاربر ثبت نام شد")
                {
                    if (user.UserName == "09224982760")
                    {
                        await _userManager.AddClaimAsync(user, new Claim("AdminNumber", "1"));
                    }
                    TempData["ConfirmCode"] = null;
                    var login = await _SignInManager.PasswordSignInAsync(ConfirmCode.PhoneNumber , Passwords.Password.Trim() , true , false);
                    return Redirect("/");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, result);
                    return View();
                }
            }

        }
        #endregion
        /////////////////////

    }
}

Shop_Stationery/Views/Signup/ConfirmCode.cshtml
@model Shop_Stationery.Models.ViewModelUser.ViewModelSignup.ViewModelExistPhoneNumber
@{
    Layout = "~/Views/Shared/_Layout_LoginAndSignup.cshtml";
}
@using Newtonsoft.Json;
@using Shop_Stationery.Models.Classes.ClassesUser.ConfirmCode;
@{
    ConfirmCode ConfirmCode = new ConfirmCode();
    ConfirmCode = JsonConvert.DeserializeObject<ConfirmCode>(ViewBag.ConfirmCode);
}

<h2 class="title-login"><b>ثبت نام</b></h2>
<br />
<form asp-action="ConfirmCode" asp-controller="Signup" method="post">
    <label class="label-top-input">کد  ارسال شده برای شماره را وارد کنید</label>
    <input type="text" asp-for="ConfirmCode" maxlength="5" inputmode="numeric" autocomplete="off" name="ConfirmCode" value="" class="Custom-Input-1" placeholder="کد تایید" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div>
        <span class="text-time-code">مانده تا دریافت مجدد کد</span>
        <button id="btn-Timer-Code" type="button" class="Custom-Button-3">
            00:00
        </button>
    </div>
    <br />
    <button type="submit" class="Custom-Button-2">
        تایید
    </button>

</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    @{
        var datatime = ConfirmCode.TimeExpiration - DateTime.Now;
    }
    @if (ConfirmCode.TimeExpiration <= DateTime.Now)
    {
        <script>
            var MyTimer = setInterval(TimerConfirmCode, 1000);
            var d = new Date(0, 0, 0, 0, 3, 0, 0);
            function TimerConfirmCode() {
                var timeNow = d.getTime();
                d.setTime(timeNow - 1000);
                if (d.getMinutes() == 0 && d.getSeconds() == 0) {
                    document.getElementById("btn-Timer-Code").innerText = "دریافت کد";
                    clearInterval(MyTimer);
                }
                else {
                    if (d.getSeconds().toString().length == 1) {
                        document.getElementById("btn-Timer-Code").innerText = "0" + d.getMinutes() + ":0" + d.getSeconds() + "";
                    }
                    else {
                        document.getElementById("btn-Timer-Code").innerText = "0" + d.getMinutes() + ":" + d.getSeconds() + "";
                    }
                }
            }
        </script>
    }
    else
    {
        <script>
        var MyTimer = setInterval(TimerConfirmCode, 1000);
        var d = new Date(0, 0, 0, 0, @datatime.Minutes, @datatime.Seconds , 0,);
        function TimerConfirmCode() {
            var timeNow = d.getTime();
            d.setTime(timeNow - 1000);
            if (d.getMinutes() == 0 && d.getSeconds() == 0) {
                document.getElementById("btn-Timer-Code").innerText = "دریافت کد";
                clearInterval(MyTimer);
            }
            else {
                if (d.getSeconds().toString().length == 1) {
                    document.getElementById("btn-Timer-Code").innerText = "0" + d.getMinutes() + ":0" + d.getSeconds() + "";
                }
                else {
                    document.getElementById("btn-Timer-Code").innerText = "0" + d.getMinutes() + ":" + d.getSeconds() + "";
                }
            }
        }
        </script>
    }
}

Shop_Stationery/Views/Signup/SubmitPassword.cshtml
@model Shop_Stationery.Models.ViewModelUser.ViewModelSubmitPassword.ViewModelSubmitPassword
@{
    Layout = "~/Views/Shared/_Layout_LoginAndSignup.cshtml";
}


<h2 class="title-login">رمز عبور</h2>
<br />
<form asp-action="SubmitPassword" asp-controller="Signup" method="post">
    <label class="label-top-input">رمز عبور را وارد کنید</label>
    <input asp-for="Password" type="password" maxlength="100" name="Password" value="" class="Custom-Input-1" placeholder="رمز عبور" />
    <input asp-for="PasswordAgain" type="password" maxlength="100" name="PasswordAgain" value="" class="Custom-Input-1" placeholder="تکرار رمز عبور" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <br />
    <button type="submit" class="Custom-Button-2">
        تایید
    </button>
</form>